### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by michelepagot** [unguiculus/job-dsl-sample#2]
Even commenting some plugins in build.gradle file I have

> gradlew.bat test --continue

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Could not resolve all files for configuration ':testPlugins'.
> Could not find blueocean-jira.jar (io.jenkins.blueocean:blueocean-jira:1.2.4).
  Searched in the following locations:
      https://jcenter.bintray.com/io/jenkins/blueocean/blueocean-jira/1.2.4/blueocean-jira-1.2.4.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Could not resolve all files for configuration ':testCompileClasspath'.
> Could not find bootstrap-core-assets.jar (org.jenkins-ci.ui:bootstrap:1.3.2).
  Searched in the following locations:
      https://jcenter.bintray.com/org/jenkins-ci/ui/bootstrap/1.3.2/bootstrap-1.3.2-core-assets.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================

BUILD FAILED

**Comment by unguiculus** [comment]
I've seen this issue, too. It's somewhat strange and looks like a Gradle issue.

**Comment by unguiculus** [comment]
Should be fixed with #4.
